INSERT INTO CABYFLOWER.TIPO_USUARIO(SEQ_TIPO_USUARIO, DES_TIPO_USUARIO)
VALUE(1, 'USUARIO COMUM')

INSERT INTO CABYFLOWER.TIPO_USUARIO(SEQ_TIPO_USUARIO, DES_TIPO_USUARIO)
VALUE(2, 'USUARIO ESTABELECIMENTO')